In [40]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler



In [41]:
data = pd.read_csv("energy.csv")
data.head()


X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28

In [42]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(data):
    # Drop duplicate rows across all columns
    data = data.drop_duplicates()
    # Drop rows with missing data across all columns
    data = data.dropna()
    return data

data = clean_data(data)
data.head()

X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28

In [43]:

data.shape

(768, 10)

In [44]:
data.isnull().sum()

X1    0
X2    0
X3    0
X4    0
X5    0
X6    0
X7    0
X8    0
Y1    0
Y2    0
dtype: int64

In [45]:
data.describe()


X1          X2          X3          X4         X5          X6  \
count  768.000000  768.000000  768.000000  768.000000  768.00000  768.000000   
mean     0.764167  671.708333  318.500000  176.604167    5.25000    3.500000   
std      0.105777   88.086116   43.626481   45.165950    1.75114    1.118763   
min      0.620000  514.500000  245.000000  110.250000    3.50000    2.000000   
25%      0.682500  606.375000  294.000000  140.875000    3.50000    2.750000   
50%      0.750000  673.750000  318.500000  183.750000    5.25000    3.500000   
75%      0.830000  741.125000  343.000000  220.500000    7.00000    4.250000   
max      0.980000  808.500000  416.500000  220.500000    7.00000    5.000000   

               X7         X8          Y1          Y2  
count  768.000000  768.00000  768.000000  768.000000  
mean     0.234375    2.81250   22.307201   24.587760  
std      0.133221    1.55096   10.090196    9.513306  
min      0.000000    0.00000    6.010000   10.900000  
25%      0.100000    1.75000   12.992500   15.620000  
50%      0.250000    3.00000   18.950000   22.080000  
75%      0.400000    4.00000   31.667500   33.132500  
max      0.400000    5.00000   43.100000   48.030000

In [46]:
indexx = data["X7"].index
indexx

RangeIndex(start=0, stop=768, step=1)

In [47]:
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

In [48]:
scaled_data[:,7].shape

(768,)

In [49]:
X = scaled_data[:,[0, 1, 2, 3, 4,5,6,7]]
X = X.astype("float")

X.ndim

type(X)

numpy.ndarray

In [50]:
scaled_data[:,8:10].shape

(768, 2)

In [51]:
y1 = scaled_data[:,[8]]
y1 = y1.astype("float")
type(y1)
y1.shape

(768, 1)

In [52]:
y2 = scaled_data[:,[9]]
y2.shape
y2

array([[0.28090493],
       [0.28090493],
       [0.28090493],
       [0.28090493],
       [0.46808511],
       [0.38998115],
       [0.38405602],
       [0.50363587],
       [0.44169135],
       [0.29814166],
       [0.33907891],
       [0.45704282],
       [0.34661998],
       [0.28440614],
       [0.27632642],
       [0.37786157],
       [0.72259628],
       [0.54861298],
       [0.53945597],
       [0.76865069],
       [0.50875303],
       [0.50579047],
       [0.50875303],
       [0.49824939],
       [0.        ],
       [0.0078104 ],
       [0.0010773 ],
       [0.00727175],
       [0.00996499],
       [0.02208457],
       [0.01050364],
       [0.02073795],
       [0.02262322],
       [0.03097226],
       [0.02235389],
       [0.02774037],
       [0.0403986 ],
       [0.03582009],
       [0.0403986 ],
       [0.03339618],
       [0.15836251],
       [0.15890116],
       [0.15755454],
       [0.15539995],
       [0.03151091],
       [0.03555077],
       [0.03178023],
       [0.030

In [53]:
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error


In [54]:
# Veriyi eğitim ve test verilerine bölün
from sklearn.linear_model import LinearRegression
from sklearn.multioutput import MultiOutputRegressor


# split the dataset into training and testing sets
X_train, X_test, y1_train, y1_test = train_test_split(X, y1, test_size = 0.30, random_state=77)
X_train, X_test, y2_train, y2_test = train_test_split(X, y2, test_size = 0.30, random_state=77)


# train the model and make predictions for heating_load
lr_heating = LinearRegression(n_jobs=-1)
y1_pred = lr_heating.fit(X_train, y1_train).predict(X_test)

# train the model and make predictions for cooling_load
lr_cooling = LinearRegression(n_jobs=-1)
y2_pred = lr_cooling.fit(X_train, y2_train).predict(X_test)

# calculate the MSE
print('MSE of predicting heating load: \n', mean_squared_error(y1_test, y1_pred).round(4))
print('MSE of predicting cooling load: \n', mean_squared_error(y2_test, y2_pred).round(4))
print('')


# calculate the RMSE
print('RMSE of predicting heating load: \n', mean_squared_error(y1_test, y1_pred, squared=False).round(4))
print('RMSE of predicting cooling load: \n', mean_squared_error(y2_test, y2_pred, squared=False).round(4))
print('')

MSE of predicting heating load: 
 0.0065
MSE of predicting cooling load: 
 0.0077

RMSE of predicting heating load: 
 0.0804
RMSE of predicting cooling load: 
 0.0877



In [62]:
# calculate the MAE
from sklearn.metrics import mean_absolute_error


print('MAE of predicting heating load: \n', mean_absolute_error(y1_test, y1_pred).round(2))
print('MAE of predicting cooling load: \n', mean_absolute_error(y2_test, y2_pred).round(2))


MAE of predicting heating load: 
 0.06
MAE of predicting cooling load: 
 0.06


In [65]:
y1_train

array([[1.20248045e-01],
       [2.26206525e-01],
       [5.31949312e-01],
       [7.20949043e-01],
       [1.84416285e-01],
       [1.64734430e-01],
       [6.90752224e-01],
       [7.22836344e-01],
       [1.45861418e-01],
       [6.41143165e-01],
       [1.47748719e-01],
       [3.20032354e-01],
       [7.23645187e-01],
       [3.47533028e-01],
       [5.38420059e-01],
       [5.63494203e-01],
       [6.07710973e-01],
       [5.21973578e-01],
       [9.13453761e-01],
       [2.28902669e-01],
       [1.38312214e-01],
       [7.07737935e-01],
       [4.80722567e-01],
       [2.44809922e-01],
       [2.31598814e-01],
       [1.71205177e-01],
       [1.64195201e-01],
       [1.93043947e-01],
       [6.10946347e-01],
       [1.61768671e-03],
       [2.45618765e-01],
       [7.35238609e-01],
       [8.97816123e-01],
       [1.50444864e-01],
       [1.87112429e-01],
       [6.57859261e-02],
       [1.39929900e-01],
       [1.46131033e-01],
       [1.22135346e-01],
       [1.66621731e-01],


In [64]:
y2_test

array([[0.46593051],
       [0.86776192],
       [0.58281713],
       [0.47885807],
       [0.08914624],
       [0.40721788],
       [0.50471317],
       [0.53891732],
       [0.09803393],
       [0.50821438],
       [0.37436036],
       [0.1211958 ],
       [0.92620522],
       [0.16967412],
       [0.41448963],
       [0.73471586],
       [0.66819284],
       [0.13816321],
       [0.22461621],
       [0.80662537],
       [0.17425263],
       [0.22946405],
       [0.10261244],
       [0.15082144],
       [0.10288177],
       [0.13385403],
       [0.51494748],
       [0.79639106],
       [0.09103151],
       [0.16967412],
       [0.50875303],
       [0.49905737],
       [0.81766765],
       [0.086453  ],
       [0.07783464],
       [0.78157824],
       [0.70993806],
       [0.09237813],
       [0.29033127],
       [0.22434689],
       [0.42607056],
       [0.09668731],
       [0.43441961],
       [0.25666577],
       [0.22973337],
       [0.15620792],
       [0.47077835],
       [0.096

In [59]:
data.corr().round(2)

X1    X2    X3    X4    X5    X6    X7    X8    Y1    Y2
X1  1.00 -0.99 -0.20 -0.87  0.83  0.00 -0.00 -0.00  0.62  0.63
X2 -0.99  1.00  0.20  0.88 -0.86 -0.00  0.00  0.00 -0.66 -0.67
X3 -0.20  0.20  1.00 -0.29  0.28 -0.00 -0.00  0.00  0.46  0.43
X4 -0.87  0.88 -0.29  1.00 -0.97 -0.00 -0.00 -0.00 -0.86 -0.86
X5  0.83 -0.86  0.28 -0.97  1.00  0.00  0.00 -0.00  0.89  0.90
X6  0.00 -0.00 -0.00 -0.00  0.00  1.00 -0.00 -0.00 -0.00  0.01
X7 -0.00  0.00 -0.00 -0.00  0.00 -0.00  1.00  0.21  0.27  0.21
X8 -0.00  0.00  0.00 -0.00 -0.00 -0.00  0.21  1.00  0.09  0.05
Y1  0.62 -0.66  0.46 -0.86  0.89 -0.00  0.27  0.09  1.00  0.98
Y2  0.63 -0.67  0.43 -0.86  0.90  0.01  0.21  0.05  0.98  1.00

In [67]:
data.describe(
)

X1          X2          X3          X4         X5          X6  \
count  768.000000  768.000000  768.000000  768.000000  768.00000  768.000000   
mean     0.764167  671.708333  318.500000  176.604167    5.25000    3.500000   
std      0.105777   88.086116   43.626481   45.165950    1.75114    1.118763   
min      0.620000  514.500000  245.000000  110.250000    3.50000    2.000000   
25%      0.682500  606.375000  294.000000  140.875000    3.50000    2.750000   
50%      0.750000  673.750000  318.500000  183.750000    5.25000    3.500000   
75%      0.830000  741.125000  343.000000  220.500000    7.00000    4.250000   
max      0.980000  808.500000  416.500000  220.500000    7.00000    5.000000   

               X7         X8          Y1          Y2  
count  768.000000  768.00000  768.000000  768.000000  
mean     0.234375    2.81250   22.307201   24.587760  
std      0.133221    1.55096   10.090196    9.513306  
min      0.000000    0.00000    6.010000   10.900000  
25%      0.100000    1.75000   12.992500   15.620000  
50%      0.250000    3.00000   18.950000   22.080000  
75%      0.400000    4.00000   31.667500   33.132500  
max      0.400000    5.00000   43.100000   48.030000